version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.22
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        managementApiSecret: Samsung99
        databases:
          default:
            connector: postgres
            host: postgres
            user: mbv
            password: Samsung99
            rawAccess: true
            port: 5432
            migrations: true
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mbv
      POSTGRES_PASSWORD: Samsung99
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
