projects:
  app:
    schemaPath: src/schema.graphql
    extensions:
      endpoints:
        dev: 'http://localhost:4444'
  prisma:
    schemaPath: 'src/generated/prisma.graphql'
    extensions:
      prisma: prisma/prisma.yml
